macos_min_version:             # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
c_stdlib_version:              # [osx and x86_64]
  - 10.13                      # [osx and x86_64]
